name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build and test'

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Check linting
      run: yarn lint

    - name: Check formating
      run: yarn format:check

    - name: Run tests
      run: yarn test

    - name: Build application
      run: yarn build
